[tool.poetry]
name = "s3worker"
version = "0.2.0"
description = "Sync local storage with S3"
authors = ["Eugen Ciur <eugen@papermerge.com>"]
readme = "README.md"
license = "MIT"

[tool.poetry.dependencies]
python = "^3.12"
botocore = "^1.34"
boto3 = "^1.34"
celery = {version = "^5.4", extras = ["redis"]}
typer = "^0.12.3"
pydantic = "^2.7.1"
pydantic-settings = "^2.2.1"
pyyaml = "^6.0.1"
pdf2image = "^1.17.0"
sqlalchemy = "^2.0.30"
psycopg2 = { version = "^2.9.2", optional = true}
psycopg2-binary = { version = "^2.9.2", optional = true}
mysqlclient = {version = "^2.2.0", optional = true}
rich = "^13.7.1"

[tool.poetry.extras]
mysql = ["mysqlclient"]
pgsql = ["psycopg2", "psycopg2-binary"]
databases = ["mysqlclient", "psycopg2"]

[tool.poetry.scripts]
s3w = 's3worker.cli.s3w:app'

[tool.poetry.group.dev.dependencies]
taskipy = "^1.12.2"

[tool.taskipy.tasks]
worker = "celery -A s3worker worker -E -c 4 --loglevel debug -Q dev-coco_s3,dev-coco_s3preview"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
